name: Generate Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        include:
          - theme: light
            suffix: ""
          - theme: dark
            suffix: "-dark"
    steps:
      - name: Overview
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/overview${{ matrix.suffix }}.svg
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: didik-maulana
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Jakarta
          config_theme: ${{ matrix.theme }}
